<?php echo $this->element->fullname->setLabel('Full Name')->setAttrib('class', 'input-medium') ?>
<?php echo $this->element->email->setLabel('Email')->setAttrib('class', 'input-medium') ?>
<?php echo $this->element->subject->setLabel('Subject')->setAttrib('class', 'input-medium') ?>
<?php echo $this->element->message->setLabel('Message')->setAttrib('class', 'input-medium')->setAttrib('rows', 10) ?>
<div class="offset2"><input class="btn btn-primary" type="submit" value="Submit"></div>