<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>DangerousPictures</title>
</head>
<body>
<header>
    <div class="navbar" data-scrollspy="scrollspy">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="#">DangerousPictures</a>
                <ul class="nav">
                    <li>
                        <a href="/admin/categories/index/page">Categories</a>
                    </li>
                    <li>
                        <a href="/admin/countries/index/page">Countries</a>
                    </li>
                    <li>
                        <a href="/admin/sources/index/page">Sources</a>
                    </li>
                    <li>
                        <a href="/admin/filters/index/page">Filters</a>
                    </li>
                    <li>
                        <a href="/admin/messages/index/page">Messages</a>
                    </li>
                </ul>
                <ul class="nav pull-right locales">
                    <li class="dropdown">
                        <a href="#locale" class="dropdown-toggle" data-toggle="dropdown">Locale&nbsp;<b
                            class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin/locale/en_US">US</a></li>
                            <li><a href="/admin/locale/de">DE</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>
<div class="container application">

<?php echo $this->layout()->content ?>

</div>

</body>
</html>