<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <?php echo $this->headLink()
    ->appendStylesheet('/css/reset.css')
//    ->appendStylesheet('/css/admin.css')
    ->appendStylesheet('/css/style.css')
    ->appendStylesheet('/css/ie6.css', 'screen', 'IE 6')
    ->appendStylesheet('/css/ie7.css', 'screen', 'IE 7')
    ?>
    <?php echo $this->headTitle() ?>
</head>
<body id="body-wrapper">
<div id="header">
    <?php echo $this->navigation()->menu($this->layout()->navigation)->setUlClass('navigation')?>
</div>
<div id="body">
    <?php echo $this->flashMessages(); ?>
    <?php echo $this->layout()->content ?>
</div>
<?php echo $this->headScript()
    ->prependFile('/js/jquery/jquery.min.js')
    ->appendFile('/js/supersleight-min.js', 'text/javascript', array('conditional' => 'IE 6'))
?>
</body>
</html>