<div class="span10 offset1"><?php echo $this->form->setAttrib('id', 'account-info-form') ?></div>
<div id="footer">
    <div class="additional-info">
        <h6>Important Page Information</h6>
        <hr>
        <p>*This website has only one user account. The username of which is always ‘admin’. The password can be reset to any that is desirable to the administrator.</p>
        <p>* Account Email is the address which can be used as an alternative to username in the ‘log-in’ screen. It is also the email address to which all the contact form messages will be sent to. Password recovery is also done through the same email.</p>
    </div>
</div>