<div class="main-pic-block-wrapper">
    <div class="main-pic-block">
        <div class="container"></div>
        <div class="shadow-text" style="display: none;">
            <h1></h1>
            <span></span>
        </div>
    </div>
</div>
<?php $this->headScript()
    ->appendFile('/js/doT.js')
    ->appendFile('/js/gallery.js')
    ->appendFile('/js/vimeo/javascript/froogaloop.min.js')
    ->appendFile('/js/modules/index/index.js')
?>