<div class="row vmargin">
    <div class="span2 pull-right">
        <div class="btn-group pull-right">
            <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">Add...<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a data-toggle="image" href="#image">Image</a></li>
                <li><a data-toggle="vimeo" href="#vimeo">Vimeo Video</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="add row vmargin hide image">
    <div class="span4 offset4">
        <form action="<?php echo $this->url(array('action' => 'save-image', 'controller' => 'media')) ?>" class="image" enctype="multipart/form-data">
            <div class="control-group">
                <label for="image" class="control-label">Image:</label>

                <div class="controls"><input type="file" class="input-file" id="image" name="image"></div>
            </div>
            <div class="control-group">
                <div class="actions pull-right">
                    <a class="btn cancel" href="#cancel">Cancel</a>
                    <a class="btn btn-primary save" href="#save">Save</a>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="add row vmargin hide vimeo">
    <div class="span4 offset4">
        <form method="post" action="<?php echo $this->url(array('action' => 'save-vimeo', 'controller' => 'media')) ?>" class="vimeo">
            <div class="control-group">
                <label for="video-url" class="control-label">URL:</label>

                <div class="controls"><input type="text" class="span4" id="video-url" name="url"></div>
            </div>
            <div class="control-group thumbnails-container hide">
                <a class="btn pull-right change-thumb" href="#preview"><i class="icon-camera"></i></a>
                <ul class="thumbnails">
                    <li>
                        <a class="thumbnail" href="#">
                            <img alt="" src="about:blank">
                        </a>
                    </li>
                </ul>
            </div>

            <div class="control-group">
                <div class="actions pull-right">
                    <a class="btn preview" href="#preview">Preview</a>
                    <a class="btn cancel" href="#cancel">Cancel</a>
                    <a class="btn btn-primary save" href="#save">Save</a>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row vmargin">
    <?php if (count($this->media) > 0): ?>
    <table class="table table-bordered">
        <tr>
            <th class="span1 center">#</th>
            <th>Thumbnail</th>
            <th class="span2 center">Actions</th>
        </tr>
        <?php foreach ($this->media as /** @var \Entities\Media $media */ $media): ?>
        <tr>
            <td class="span1 center vcenter">
                <div class="down-btn-container up">
                    <a class="btn icon-arrow-up reorder" data-id="<?php echo $media->getId() ?>" href="<?php echo $this->url(array('action' => 'up')) ?>"></a>
                </div>
                <div class="down-btn-container down">
                    <a class="btn icon-arrow-down reorder" data-id="<?php echo $media->getId() ?>" href="<?php echo $this->url(array('action' => 'down')) ?>"></a>
                </div>
            </td>
            <td>
                <ul class="thumbnails">
                    <li><a href="#" class="thumbnail">
                        <img src="<?php echo $this->thumbnail($media, 's') ?>" alt="">
                    </a></li>
                </ul>
            </td>
            <td class="center vcenter">
                <a class="btn btn-large btn-danger" href="<?php echo $this->url(array('action' => 'delete', 'id' => $media->getId())) ?>"><i class="icon-trash"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php else: ?>
    <h2>No media files found</h2>
    <?php endif; ?>
</div>
<div id="mediaModal" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3>&nbsp;</h3>
    </div>
    <div class="modal-body" align="center"></div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
    </div>
</div>
<script type="text/html" id="vimeoPreview">
    <iframe src="http://player.vimeo.com/video/{{=it.vimeo_id}}?title=0&byline=0&portrait=0&color=3EFFDA" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</script>
<?php $this->headScript()
    ->appendFile('/js/doT.js')
    ->appendFile('/js/modules/media/index.js') ?>