<div class="topmenu-line">&nbsp;</div>
<ul class="submenu">
    <li><a data-toggle="image" href="#">IMAGES</a></li>
    <li><a data-toggle="vimeo" href="#">VIDEO</a></li>
</ul>

<div id="upload-box">
    <div class="add image hide">
        <form action="<?php echo $this->url(array('action' => 'save-image', 'controller' => 'media')) ?>" method="post" class="image" enctype="multipart/form-data">
            <div class="psevdo-upload-box">&nbsp;</div>
            <input name="image" class="file" type="file" size="36">
        </form>
    </div>
    <div class="add vimeo hide">
        <form action="<?php echo $this->url(array('action' => 'save-vimeo', 'controller' => 'media')) ?>" method="post" class="vimeo">
            <input class="url" size="36" type="text" name="url" id="url">
            <button class="upload">&nbsp;</button>
        </form>
    </div>
</div>

<div id="files-box-wrapper">
    <?php if (count($this->media) > 0): ?>
    <div id="files-box-border">
        <ul id="files-box">
            <?php foreach ($this->media as /** @var \Entities\Media $media */ $media): ?>
            <li class="file-item">
                <div class="file-name">Image Name</div>
                <div class="file-content">
                    <form method="post" action="<?php echo $this->url(array('action' => 'save', 'controller' => 'media')) ?>">
                        <input type="hidden" name="id" value="<?php echo $media->getId() ?>">
                        <div class="file-number">#<br><?php echo $media->getPosition() ?: 'u' ?>
                            <a class="unpos" href="<?php echo $this->url(array('controller' => 'media', 'action' => 'unpos', 'id' => $media->getId())) ?>">&nbsp;</a></div>
                        <div class="file-preview"><img src="<?php echo $this->thumbnail($media, 's') ?>" alt="<?php echo $media->getTitle() ?>"></div>
                        <div class="file-info-wrapper">
                            <input type="text" name="title" class="file-info" value="<?php echo $media->getTitle() ?>" title="Title">
                            <input type="text" name="description" class="file-info" value="<?php echo $media->getDescription() ?>" title="Description">
                            <input type="text" name="link" class="file-info" value="<?php echo $media->getLink() ?>" title="Hyperlink">
                        </div>
                        <a class="button file-save">SAVE</a>
                        <a href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'media', 'id' => $media->getId())) ?>" class="button file-delete">DEL</a>
                    </form>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php else: ?>
    <h2>No media files found</h2>
    <?php endif; ?>
</div>

<div id="mediaModal" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3>&nbsp;</h3>
    </div>
    <div class="modal-body" align="center"></div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
    </div>
</div>
<script type="text/html" id="vimeoPreview">
    <iframe src="http://player.vimeo.com/video/{{=it.vimeo_id}}?title=0&byline=0&portrait=0&color=3EFFDA" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</script>

<?php $this->headScript()
    ->appendFile('/js/doT.js')
    ->appendFile('/js/jquery/jquery.form.js')
    ->appendFile('/js/jquery/jquery.scroll.min.js')
    ->appendFile('/js/bootstrap.min.js')
    ->appendFile('/js/modules/media/index.js') ?>

<?php $this->headLink()->appendStylesheet('/css/scrollbar.css'); ?>