<h2>Account Details</h2>
<div class="line">&nbsp;</div>
    <?php echo $this->element->password->setLabel('Account Password')->setAttrib('class', 'span6') ?>
    <?php echo $this->element->confirm->setLabel('Confirm Account Password')->setAttrib('class', 'span6') ?>
    <?php echo $this->element->email->setLabel('Account Email')->setAttrib('class', 'span6') ?>
<h2>External Connections</h2>
<div class="line">&nbsp;</div>
    <?php echo $this->element->twitter->setLabel('Twitter Account URL')->setAttrib('class', 'span6') ?>
    <?php echo $this->element->facebook->setLabel('Facebook Account URL')->setAttrib('class', 'span6') ?>
    <?php echo $this->element->vimeo->setLabel('Vimeo Account URL')->setAttrib('class', 'span6') ?>
<dl>
    <dt>&nbsp;</dt>
    <dd><button>Save Changes</button></dd>
</dl>