<div id="register" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3>Create new user with Admin privileges</h3>
    </div>
    <div class="modal-body">
        <?php echo $this->form->setAttrib('class', 'form-horizontal') ?>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <a href="#" class="btn btn-primary">Register</a>
    </div>
</div>
<?php $this->headScript()->appendFile('/js/modules/root/index.js') ?>